# Generated by Django 5.1.4 on 2025-03-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=150, verbose_name="ФИО")),
                ("post", models.CharField(max_length=150, verbose_name="Должность сотрудника")),
                ("task_count", models.PositiveIntegerField(default=0, verbose_name="Количество задач сотрудника")),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название задачи")),
                (
                    "deadline",
                    models.DateField(help_text="Укажите дату дэдлайна", verbose_name="День до выполнения задачи"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Создана", "Created"), ("Выполняется", "Processing"), ("Завершена", "Completed")],
                        default="Создана",
                        verbose_name="Статус задачи",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания задачи")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_task",
                        to="employees.employee",
                        verbose_name="Исполнитель задачи",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите родительскую задачу",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.task",
                        verbose_name="Связаная задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
