# Generated by Django 5.1.4 on 2025-03-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="task_count",
        ),
    ]
