# Generated by Django 5.1.4 on 2025-03-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_remove_employee_task_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Телеграм чат-id"),
        ),
    ]
