# Generated by Django 5.1.7 on 2025-03-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("Создана", "Created"), ("Выполняется", "Processing"), ("Завершена", "Completed")],
                default="Создана",
                max_length=20,
                verbose_name="Статус задачи",
            ),
        ),
    ]
